"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import Popup from "./ui/popup";
import { Suspense, useEffect } from "react";
import Toast from "./ui/toast";
import IRequest from "./ui/i-request";
import { ifetch } from "./core/api";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = `${inter.className} `;

  return (
    <html lang="en">
      <body className={bodyClassName}>
        <RecoilRoot>
          <Suspense>
            <Toast />
            {children}
            <Popup />
          </Suspense>
          <IRequest/>
        </RecoilRoot>
      </body>
    </html>
  );
}
